ALTER TABLE `automation_rules`
  MODIFY `trigger_type` ENUM(
    'BIRTHDAY',
    'ORDER_SHIPPING_STATUS',
    'ORDER_DELIVERED_PAID',
    'CUSTOMER_CREATED',
    'ORDER_CREATED',
    'ORDER_CONFIRMED',
    'ORDER_SHIPPED',
    'ORDER_DELIVERED',
    'ORDER_PARTIAL_DELIVERED',
    'ORDER_CANCELLED',
    'PAYMENT_SUCCESS',
    'PAYMENT_FAILED',
    'VOUCHER_CREATED',
    'VOUCHER_ACTIVATED',
    'VOUCHER_USED',
    'VOUCHER_EXPIRING_3D',
    'VOUCHER_EXPIRED',
    'BIRTHDAY_TODAY',
    'CUSTOMER_INACTIVE_30D',
    'CUSTOMER_INACTIVE_60D'
  ) NOT NULL;

ALTER TABLE `message_automation_executions`
  MODIFY `trigger_type` ENUM(
    'BIRTHDAY',
    'ORDER_SHIPPING_STATUS',
    'ORDER_DELIVERED_PAID',
    'CUSTOMER_CREATED',
    'ORDER_CREATED',
    'ORDER_CONFIRMED',
    'ORDER_SHIPPED',
    'ORDER_DELIVERED',
    'ORDER_PARTIAL_DELIVERED',
    'ORDER_CANCELLED',
    'PAYMENT_SUCCESS',
    'PAYMENT_FAILED',
    'VOUCHER_CREATED',
    'VOUCHER_ACTIVATED',
    'VOUCHER_USED',
    'VOUCHER_EXPIRING_3D',
    'VOUCHER_EXPIRED',
    'BIRTHDAY_TODAY',
    'CUSTOMER_INACTIVE_30D',
    'CUSTOMER_INACTIVE_60D'
  ) NOT NULL;
